version: "2"
volumes:
  takebot-redis-data: { driver: local }
  takebot-config: { driver: local }

services:
  ########################
  # Third-party services #
  ########################

  redis:
    image: redis:5.0.0
    volumes:
      - takebot-redis-data:/data
    ports:
      - "16379:6379"

  #####################################
  # Development-specific applications #
  #####################################

  takebot:
    image: node:11.0.0
    command: ["bin/takebot"]
    environment:
      HISTFILE: "/config/.bash_history"
    links:
      - redis
    volumes:
      - 'takebot-config:/config'
    ports:
      - "3000:3000"
    working_dir: /app
